### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by 13201547376-123** [adomasven/gsw13#1]
运行时出现缺失cymriy.h,有人有相关的库文件吗。

**Comment by DGQAQ** [comment]
lost cymriy.h

**Comment by DGQAQ** [comment]
> 运行时出现缺失cymriy.h，有人有相关的库文件吗。
请问你的问题解决了吗

**Comment by adomasven** [comment]
I'm sorry, I'm not able to provide feedback in non-English languages and frankly this project is so old I barely remember the details anyway. Closing and shutting down issue creation.
